version: '3.9'

services:
  jhaen-parser:
    container_name: jhaen_parser
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - jhaen_parser_data:/data

  n8n:
    container_name: jhaen_n8n
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: Jhaen-n8n-2025!
      WEBHOOK_URL: https://angular-studio-doorbell.ngrok-free.dev
    volumes:
      - jhaen_n8n_data:/home/node/.n8n

volumes:
  jhaen_n8n_data:
  jhaen_parser_data:
